[package]
name = "henceforth"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.50", features = ["derive"] }
colored = "3.1.1"

[dev-dependencies]
pretty_assertions = "1.4.1"



